version: '3.7'
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - /d/zero/virt/mutual/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=vera
      - POSTGRES_USER=vera
      - POSTGRES_PASSWORD=q12345
